server:
    port: 8082
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:dronedb
        username: sa
        password: password
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect